# use newer ubuntu versions
sudo: required
dist: trusty
language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:zoogie/sdl2-snapshots'
          packages:
            - gcc-5
            - g++-5
            - libsdl2-dev
            - cmake
      env:
        - CC_COMPILER=gcc-5
        - CXX_COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:zoogie/sdl2-snapshots'
          packages:
            - clang-3.5
            - libsdl2-dev
            - cmake
      env:
        - CC_COMPILER=clang-3.5
        - CXX_COMPILER=clang++-3.5
script:
    - cmake -DCMAKE_C_COMPILER=$CC_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"
    - make
